###############################################################################
# Created by write_sdc
# Tue Apr 14 08:14:59 2026
###############################################################################
current_design axi4_full_basic
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 15.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[0]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[10]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[11]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[12]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[13]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[14]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[15]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[16]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[17]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[18]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[19]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[1]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[20]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[21]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[22]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[23]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[24]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[25]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[26]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[27]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[28]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[29]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[2]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[30]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[31]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[3]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[4]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[5]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[6]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[7]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[8]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {araddr[9]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arid[0]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arid[1]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arid[2]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arid[3]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arvalid}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[0]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[10]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[11]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[12]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[13]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[14]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[15]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[16]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[17]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[18]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[19]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[1]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[20]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[21]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[22]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[23]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[24]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[25]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[26]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[27]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[28]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[29]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[2]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[30]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[31]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[3]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[4]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[5]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[6]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[7]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[8]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awaddr[9]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awid[0]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awid[1]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awid[2]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awid[3]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awlen[0]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awlen[1]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awlen[2]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awlen[3]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awlen[4]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awlen[5]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awlen[6]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awlen[7]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awsize[0]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awsize[1]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awsize[2]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awvalid}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bready}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rready}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rstn}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[0]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[10]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[11]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[12]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[13]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[14]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[15]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[16]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[17]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[18]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[19]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[1]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[20]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[21]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[22]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[23]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[24]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[25]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[26]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[27]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[28]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[29]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[2]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[30]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[31]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[3]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[4]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[5]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[6]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[7]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[8]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wdata[9]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wlast}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wstrb[0]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wstrb[1]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wstrb[2]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wstrb[3]}]
set_input_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wvalid}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {arready}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {awready}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bid[0]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bid[1]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bid[2]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bid[3]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bresp[0]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bresp[1]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {bvalid}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[0]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[10]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[11]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[12]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[13]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[14]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[15]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[16]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[17]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[18]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[19]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[1]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[20]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[21]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[22]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[23]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[24]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[25]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[26]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[27]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[28]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[29]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[2]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[30]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[31]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[3]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[4]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[5]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[6]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[7]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[8]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rdata[9]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rid[0]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rid[1]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rid[2]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rid[3]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rlast}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rresp[0]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rresp[1]}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rvalid}]
set_output_delay 3.0000 -clock [get_clocks {clk}] -add_delay [get_ports {wready}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {arready}]
set_load -pin_load 0.0334 [get_ports {awready}]
set_load -pin_load 0.0334 [get_ports {bvalid}]
set_load -pin_load 0.0334 [get_ports {rlast}]
set_load -pin_load 0.0334 [get_ports {rvalid}]
set_load -pin_load 0.0334 [get_ports {wready}]
set_load -pin_load 0.0334 [get_ports {bid[3]}]
set_load -pin_load 0.0334 [get_ports {bid[2]}]
set_load -pin_load 0.0334 [get_ports {bid[1]}]
set_load -pin_load 0.0334 [get_ports {bid[0]}]
set_load -pin_load 0.0334 [get_ports {bresp[1]}]
set_load -pin_load 0.0334 [get_ports {bresp[0]}]
set_load -pin_load 0.0334 [get_ports {rdata[31]}]
set_load -pin_load 0.0334 [get_ports {rdata[30]}]
set_load -pin_load 0.0334 [get_ports {rdata[29]}]
set_load -pin_load 0.0334 [get_ports {rdata[28]}]
set_load -pin_load 0.0334 [get_ports {rdata[27]}]
set_load -pin_load 0.0334 [get_ports {rdata[26]}]
set_load -pin_load 0.0334 [get_ports {rdata[25]}]
set_load -pin_load 0.0334 [get_ports {rdata[24]}]
set_load -pin_load 0.0334 [get_ports {rdata[23]}]
set_load -pin_load 0.0334 [get_ports {rdata[22]}]
set_load -pin_load 0.0334 [get_ports {rdata[21]}]
set_load -pin_load 0.0334 [get_ports {rdata[20]}]
set_load -pin_load 0.0334 [get_ports {rdata[19]}]
set_load -pin_load 0.0334 [get_ports {rdata[18]}]
set_load -pin_load 0.0334 [get_ports {rdata[17]}]
set_load -pin_load 0.0334 [get_ports {rdata[16]}]
set_load -pin_load 0.0334 [get_ports {rdata[15]}]
set_load -pin_load 0.0334 [get_ports {rdata[14]}]
set_load -pin_load 0.0334 [get_ports {rdata[13]}]
set_load -pin_load 0.0334 [get_ports {rdata[12]}]
set_load -pin_load 0.0334 [get_ports {rdata[11]}]
set_load -pin_load 0.0334 [get_ports {rdata[10]}]
set_load -pin_load 0.0334 [get_ports {rdata[9]}]
set_load -pin_load 0.0334 [get_ports {rdata[8]}]
set_load -pin_load 0.0334 [get_ports {rdata[7]}]
set_load -pin_load 0.0334 [get_ports {rdata[6]}]
set_load -pin_load 0.0334 [get_ports {rdata[5]}]
set_load -pin_load 0.0334 [get_ports {rdata[4]}]
set_load -pin_load 0.0334 [get_ports {rdata[3]}]
set_load -pin_load 0.0334 [get_ports {rdata[2]}]
set_load -pin_load 0.0334 [get_ports {rdata[1]}]
set_load -pin_load 0.0334 [get_ports {rdata[0]}]
set_load -pin_load 0.0334 [get_ports {rid[3]}]
set_load -pin_load 0.0334 [get_ports {rid[2]}]
set_load -pin_load 0.0334 [get_ports {rid[1]}]
set_load -pin_load 0.0334 [get_ports {rid[0]}]
set_load -pin_load 0.0334 [get_ports {rresp[1]}]
set_load -pin_load 0.0334 [get_ports {rresp[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {arvalid}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awvalid}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {bready}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rready}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rstn}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wlast}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wvalid}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {araddr[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {arid[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {arid[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {arid[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {arid[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awaddr[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awid[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awid[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awid[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awid[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awlen[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awlen[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awlen[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awlen[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awlen[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awlen[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awlen[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awlen[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awsize[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awsize[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {awsize[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wdata[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wstrb[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wstrb[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wstrb[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {wstrb[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_fanout 4.0000 [current_design]
